try to fix the action to use ubuntu

diff --git a/.github/workflows/readme-renderer.yaml b/.github/workflows/readme-renderer.yaml
--- a/.github/workflows/readme-renderer.yaml
+++ b/.github/workflows/readme-renderer.yaml
@@ -1,52 +1,32 @@
-# This is a basic workflow to help you get started with Actions
-
-# Controls when the action will run
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: master
+    paths: ['**.Rmd']
 
-name: render-readme
+name: render-rmarkdown
 
 jobs:
-  render-readme:
-    # The type of runner that the job will run on
-    runs-on: macOS-latest
+  render-rmarkdown:
+    runs-on: ubuntu-latest
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-
     steps:
       - name: Checkout repo
         uses: actions/checkout@v2
         with:
-          fetch-depth: 0 
+          fetch-depth: 0
+
+      - uses: r-lib/actions/setup-pandoc@v1
 
       - uses: r-lib/actions/setup-r@v1
-      
-      - uses: r-lib/actions/setup-pandoc@v1
-      
+
       - uses: r-lib/actions/setup-renv@v1
-    
-      - name: Install dependencies on MacOS
-        if: runner.os == 'macOS'
-        run: |
-          brew install cairo libgit2
 
-      - name: Query dependencies
-        run: |
-          install.packages('remotes')
-          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
-        shell: Rscript {0}
-    
-      - name: Cache R packages
-        uses: actions/cache@v2
+      - uses: r-lib/actions/setup-r-dependencies@v1
         with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
-          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
-
-      # install packages
-      - name: install rmarkdown
-        run: Rscript -e 'install.packages(c("rmarkdown","remotes"))'
+          extra-packages: [rmarkdown,mgcv]
+      
       
       - name: install gratia
         run: Rscript -e 'remotes::install_github("gavinsimpson/gratia", upgrade_dependencies = FALSE)'
@@ -54,11 +34,10 @@ jobs:
       # Render README.md using rmarkdown
       - name: render README
         run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
-
-      - name: commit rendered README
+      
+      - name: Commit results
         run: |
           git config --local user.name "$GITHUB_ACTOR"
           git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
-          git add README.md man/figures/README-*
-          git commit -m "Re-build README.md" || echo "No changes to commit"
-          git push origin || echo "No changes to commit"
+          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
+          git push origin || echo "No changes to commit"# This is a basic workflow to help you get started with Actions
